repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uv run --locked --group dev ruff check --force-exclude
        language: system
        args: [--fix, --exit-non-zero-on-fix]
        files: ^(humancompiler_scheduler|tests|examples)/.*\.py$
        types_or: [python, pyi, jupyter]
        require_serial: true
      - id: ruff-format
        name: ruff format
        entry: uv run --locked --group dev ruff format --force-exclude
        language: system
        files: ^(humancompiler_scheduler|tests|examples)/.*\.py$
        types_or: [python, pyi, jupyter]
        require_serial: true
      - id: mypy
        name: mypy
        entry: uv run --locked --group dev mypy
        language: system
        pass_filenames: false
        types: [python]
      - id: pyright
        name: pyright
        entry: uv run --locked --group dev pyright
        language: system
        pass_filenames: false
        types: [python]
      - id: pytest
        name: pytest
        entry: uv run --locked --group dev pytest -m "not cp_sat"
        language: system
        pass_filenames: false
        types: [python]
